### ISSUE TITLE
other issues

### ISSUE THREAD

**Issue by aarthiaarthi8** [harshitv804/LawGPT#1]
Hello sir ,I need the modules ,frameworks, tools used in this project . provide me sir

**Comment by harshitv804** [comment]
You can find it in [requirements.txt](https://github.com/harshitv804/LawGPT/blob/main/requirements.txt). To know about this project, these are the prerequisites:
- Retrieval-Augmented Generation (RAG)
- Prompt Engineering
- Inferencing with Large Language Models (LLMs)
- Streamlit
- Langchain
- Vector Embedding models & database

Hope this helps. Closing this Issue.
Thanks!
