### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by hemanthreddy243** [harshitv804/LawGPT#2]

**Comment by hemanthreddy243** [comment]
executing the 3 step is little  bit difficult and required more steps on that to tackle it

**Comment by harshitv804** [comment]
Hi, `Ingest.py` basically used to split the pdf into chunks of tokens, create vector embeddings of those chunks using the embedding model and then saves them in the FAISS vector database locally. This whole process will consume more CPU and RAM so I suggest to run this in cloud platform where, they offer more compute for free. There is being a frequent updates in the documentation so I suggest you to go through the basics of Langchain and their docs for the latest updates.

Thank You
