### ISSUE TITLE
With TogetherAI

### ISSUE THREAD

**Issue by Chanaoui** [harshitv804/LawGPT#4]
i get this error : 

**ValueError: Together received an invalid payload: { "error": { "message": "Invalid API key provided. You can find your API key at https://api.together.xyz/settings/api-keys.", "type": "invalid_request_error", "param": null, "code": "invalid_api_key" } }**

**Comment by harshitv804** [comment]
Looks like invalid_api_key. Get your api key from [https://api.together.xyz/settings/api-keys](https://api.together.xyz/settings/api-keys) and follow from step 4 of the instruct.
